[project]
name = "new-proyect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "streamlit>=1.54.0",
    "streamlit-folium>=0.26.1",
    "supabase>=2.28.0",
]
